name: Weather-App Build Pipeline

# Definición de eventos
on:
  push:
    branches:
      - main
      - dev

    paths:
      - tareas/weather-app/**
      - .github/workflows/weather-app-build.yml 

# Trabajos

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 14
        uses: actions/setup-java@v3
        with:
          java-version: '14'
          distribution: 'adopt'
          server-id: 'github'
          cache: 'maven'
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build with Maven
        run: mvn -B package assembly:single --file tareas/weather-app/pom.xml
      - name: Configure Git user
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
      - name: Publish JAR Dry Run
        run: mvn -B release:prepare release:perform -DdryRun --file tareas/weather-app/pom.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  




